allegiance = "enemy"

# Sprites to render
base_asset_path = "unit.enemy-base-1"
hands_asset_path = "unit.spear-hands-1"
projectile_asset_path = "projectile.spear-1"

# How many pixels a unit moves in a second
walk_speed = -2.5

# Interval in seconds for when a new projectile is thrown
projectile_spawn_interval = 10
# Don't let the projectile spawn in the ground
projectile_spawn_offset = { x = 0, y = -10 }
# How fast a projectile is thrown
projectile_velocity = 70
# How long the hands are hidden after launching a projectile in seconds
hide_hands_delay = 9
